### ISSUE TITLE
Some package use wrong vscode import leading to dependency resolution issues down the line

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#568]
There are some package (for example `@codingame/monaco-vscode-javascript-default-extension` and all `@codingame/monaco-vscode-language-pack`-*) that define vscode as:
`"vscode": "npm:@codingame/monaco-vscode-api@13.1.1"`
and not like:
`"vscode": "npm:@codingame/monaco-vscode-extension-api@13.1.1"`

I upgraded `monaco-languageclient` in a project and then it complains that `vscode/localExtensionHost` cannot be resolved, because all vscode packages have been deduped to `"vscode": "npm:@codingame/monaco-vscode-api@13.1.1"`

Workaround is to enforce the correct version via override:
```yaml
  "overrides": {
    "vscode": "npm:@codingame/monaco-vscode-extension-api@13.1.1"
  }
```
