### ISSUE TITLE
Disable or Completely Remove the Command Palette

### ISSUE THREAD

**Issue by JairTorres1003** [CodinGame/monaco-vscode-api#596]
I’m currently using `monaco-vscode-api`, and I’d like to know if there is a way to disable access to the command palette or prevent the service that manages it from loading altogether.

<img width="746" alt="Image" src="https://github.com/user-attachments/assets/a2c83426-f4d2-4cfa-979b-8bcb876c636f" />

My main goal is to use the editor with VS Code themes, but I don’t need other functionalities like the command palette.

**What I’ve Tried**
For now, I’m hiding the command palette using CSS:

```css
.quick-input-widget.show-file-icons, .quick-input-widget.show-file-icons * {
    pointer-events: none;
    user-select: none;
    display: none !important;
    height: 0;
    opacity: 0;
    width: 0 !important;
}

```
This prevents the element from being displayed, even when pressing shortcuts like `Cmd + P` or `Cmd + K + T`. However, I’d like to know if there is a more proper way to completely disable it via configuration or code instead of just hiding it with CSS.

> Ideally, it would also be possible to disable the associated keyboard shortcuts as well as prevent access through the context menu.

**Question**
Is there an API or setting in `monaco-vscode-api` to disable the command palette or prevent it from loading? Or is CSS the only viable solution?

**Playground for Testing**
I've created a playground where you can test this behavior:

🔗 [StackBlitz Playground](https://stackblitz.com/edit/vitejs-vite-ca7ddmeb?file=src%2Fmain.tsx)

I added two buttons—one to apply the CSS and another to remove it—so you can see what I’m trying to achieve.

Thanks in advance for any guidance!
